### ISSUE TITLE
Move logic to Services

### ISSUE THREAD

**Issue by kesar** [EOSEssentials/EOSTracker#1]
Right now code is inside of components it should be moved to proper services

**Comment by tianyangj** [comment]
Hi kesar, I am a front end developer with Angular experiences and I like to contribute to this project. Do you have a code contribute guide? If you need any help, please let me know.

**Comment by kesar** [comment]
hey @tianyangj it would be great, I am planning to start some bounties in EOS for improvements, do you use telegram? if you do, join in https://t.me/eostracker and we can have a chat!

**Comment by kesar** [comment]
done in:
https://github.com/EOSEssentials/EOSTracker/pull/50
https://github.com/EOSEssentials/EOSTracker/pull/44
https://github.com/EOSEssentials/EOSTracker/pull/43
