### ISSUE TITLE
Be able to view a smart contract and its corresponding interface

### ISSUE THREAD

**Issue by jonericcook** [EOSEssentials/EOSTracker#10]
This is a suggestion on how to improve eostracker. Upon reviewing eostracker I noticed there was no feature that allowed me to view the source code nor the interface for a given smart contract. A reference for how this could look is can be seen below:

View the smart contact's source code:
https://etherscan.io/address/0xd0a6e6c54dbc68db5db3a091b171a77407ff7ccf#code

View the smart contact's interface:
https://etherscan.io/address/0xd0a6e6c54dbc68db5db3a091b171a77407ff7ccf#readContract

**Comment by kesar** [comment]
@joneric Thanks for the suggestion! Right now the only thing that you can see its the ABI ( for example in http://eostracker.io/accounts/eos ). I am working in a ABI to "HTML Form" similar to the second link that you posted :) 

The source code could be also a good improvement. I know that in etherscan you need to upload your .sol file and backend should compile it and match it with the code in the blockchain.

**Comment by jonericcook** [comment]
@kesar - Awesome!

**Comment by kesar** [comment]
splitted here: https://github.com/EOSEssentials/EOSTracker/issues/51 & https://github.com/EOSEssentials/EOSTracker/issues/49
