### ISSUE TITLE
transaction.messages is null in dawn 3.x

### ISSUE THREAD

**Issue by ghoti143** [EOSEssentials/EOSTracker#11]
In the 3.x branch of EOS, messages has been renamed to actions.  The transactions.component.html and transaction.component.html files will need to be updated to account for this.  In addition, code in the /contracts folder will need to change.

**Comment by kesar** [comment]
Great idea, we could create a branch dawn3 for client & API and keep it out of master till end of Q1 when they will officially switch to dawn3

**Comment by kesar** [comment]
There seems to be a bunch of upcoming changes in db plugin, we can see the comments of Heifner there :)
 https://docs.google.com/document/d/1E6BQVX1E8jsCzJIpFWV_B3hfA7Br6iiFlUiWZJpJ3zM/edit#

https://github.com/EOSIO/eos/issues/1403
