### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by kesar** [EOSEssentials/EOSTracker#16]
It seems that tracker is very popular in China, we should allow multi language.

<img width="353" alt="screen shot 2018-02-24 at 18 12 08" src="https://user-images.githubusercontent.com/1288106/36641049-1bc998fe-1a2a-11e8-9ba9-d987c5dde12a.png">

https://medium.com/letsboot/translate-angular-4-apps-with-ngx-translate-83302fb6c10d
https://github.com/LuisJoseSanchez/angular-multi-language-simple-app

**Comment by petervalencic** [comment]
Added Slovenian, Croatian and Italian language

waiting for:
Dutch(Netherland), French and Russian translate

**Comment by kesar** [comment]
done the support, we can keep adding languages 👍
