### ISSUE TITLE
Make API optional?

### ISSUE THREAD

**Issue by kesar** [EOSEssentials/EOSTracker#17]
It would be interesting to understand what endpoints we really need. Mostly all the transactions / blocks can be queried using the blockchain.

The main points that could be moved to a eosd plugin are:

- account list?
- global stats (number of transactions, blocks, accounts, msgs..)
- Producer stats

I am thinking about to allow the block explorer to choose between blockchain + API or just blockchain (hiding the sections that we can't populate with data).

**Comment by ghoti143** [comment]
Great thought.  I played around with this idea a while back.  I'm a bit confused about the two different APIs.  There's the plugin APIs that get served out via eosiod.  e.g. http://testnet1.eos.io/v1/chain/get_info.  But then there's a standalone one: https://t1api.eos.io/v1/docs/

The standalone one looks a bit more robust.  I think it might be a good candidate to replace the custom EOSTracker api which wraps calls to mongo.  I've played around with it a bit, but haven't had much success as of late.  Keep getting 504 gateway timeout errors.

Here's a postman collection that I've been using to interact with the t1api:  https://www.getpostman.com/collections/33cac222e50644e6648f

**Comment by kesar** [comment]
Yeah, the reason is because t1api is a backend built here https://github.com/Tandemly/eos-api-service so I would avoid having dependencies on more third parties. We have some custom queries like the producers, or stats that it would be hard to wait for them to create those endpoints.

Ideally I think we could use the most possible endpoints from eosd, and have a small API just for the custom ones. (and eventually, have those custom ones in an eosd plugin, time to learn more c++ :D  :))

**Comment by ghoti143** [comment]
Ahh -- that's where that API service lives.  Thanks, I've been looking for the code.  Afaik, the eos-api-service relies on mongodb -- which from what I've heard may not be the long term solution for storage.

Yes -- I agree -- probably best to stick with eosd.  The current chain_api is pretty limited, though, I think.  I'm not sure that you can request a list of blocks -- just a specific one.  Also -- while the get_block response does contain the transactions, I don't think you can request a specific transaction.

Like you say -- I think doing this through plugins in the best route.  The obvious advantage to using a plugin vs. a 3rd party is that when/if the database changes, the EOS Tracker will be insulated from those changes.
