### ISSUE TITLE
Duplicated code related to tables

### ISSUE THREAD

**Issue by kesar** [EOSEssentials/EOSTracker#3]
The simple table + pagination system could be moved to its own component to avoid copy/paste

**Comment by tianyangj** [comment]
I just pushed a new branch called material, https://github.com/EOSEssentials/EOSTracker/tree/material, where I started to implement a shared table component. I then created two new components with new routes /actions/v1 and /accounts/v1 to use the shared table component. The new routes are demo only so we can compare UI easily.  

The new UI is using material design. My goal is to use material to replace jQuery and bootstrap.

**Comment by kesar** [comment]
Nice! :D Do you have it by any chance in some url?

**Comment by tianyangj** [comment]
Sure, it is deployed here.

- https://eostrackerio.firebaseapp.com/actions/v1
- https://eostrackerio.firebaseapp.com/accounts/v1

**Comment by kesar** [comment]
looking promising! does material has something to easy do the resizing / hiding fields for mobile? 25% of visitors are mobile for the tracker

**Comment by tianyangj** [comment]
I added @angular/flex-layout package, https://github.com/angular/flex-layout, it should handle most of our responsive and adaptive features using flex.

**Comment by tianyangj** [comment]
We can close this issue now. "app-table" component in shared module should satisfy basic table requirements.
