### ISSUE TITLE
Integration of ng-bootstrap [Refactoring]

### ISSUE THREAD

**Issue by sushrest** [EOSEssentials/EOSTracker#36]
@kesar I would like to put a proposal of integration of ng-bootstrap
https://ng-bootstrap.github.io/#/getting-started

**Comment by kesar** [comment]
sounds good! if it doesnt break the current design, it would be a nice improvement :) 👏

**Comment by kesar** [comment]
is there any update on this? if not I will close it 👍

**Comment by kesar** [comment]
reopen if refactoring happen thx!
