### ISSUE TITLE
Handle errors when search

### ISSUE THREAD

**Issue by tianyangj** [EOSEssentials/EOSTracker#45]
When user search anything other than well formed block id or account key or transaction id, an unhandled exception is thrown, e.g., search for "eos". We probably should consider handle the exceptions in this case.

**Comment by kesar** [comment]
👍 yes, It was in my list of things to handle. I think from backend we are already getting a 404 (if not we should, I can change that part if needed).

**Comment by tianyangj** [comment]
In search component, if API encounters any errors (400 and 500), we now treat search result as null.
