### ISSUE TITLE
Under maintenance alert

### ISSUE THREAD

**Issue by kesar** [EOSEssentials/EOSTracker#47]
Request get_info periodically from blockchain, on launch & each 20 secs and match our latest block stored with the one from blockchain. If there is a gap of > 600 we should show a warning message near the <h1>

**Comment by tianyangj** [comment]
Good idea, where do you think we should show the warning message? Also what message should we show to the user. Currently the dashboard pulls get_info and latest block from API every 5 seconds, we can show the alert in dashboard. However, If we show this alert in other places, we need to pull get_info and latest block in a global location.

**Comment by kesar** [comment]
just in dashboard could be fine 👌
