### ISSUE TITLE
How to connect with local EOSTracker-API?

### ISSUE THREAD

**Issue by dbarobin** [EOSEssentials/EOSTracker#63]
I notice EOSTracker have `environment.tsts` and `environment.prod.tsts` configuration file, and the content shows the EOSTracker connect to the external url.

So I have one problem. How to connect with local [EOSTracker-API](https://github.com/EOSEssentials/EOSTracker-API)? I build EOSTracker-API successfully and sync with mainnet with **sql_db_plugin**.

Thanks.

**Comment by tianyangj** [comment]
I normally just use the production EOSTracker-API for development. However, if you already have a local api up and running, you can just replace "apiUrl: 'https://api.eostracker.io'" in environment.ts, to whatever you are hosting API locally.

**Comment by dbarobin** [comment]
OK, Get it. Thanks.
