### ISSUE TITLE
how change refresh time for dashboard?

### ISSUE THREAD

**Issue by newbieh4cker** [EOSEssentials/EOSTracker#65]
in src\app\dashboard\dashboard\dashboard.component.ts file.

I've changed every timer function as timer(0, 500).
installed with "npm install --unsafe-perm --no-optional" command.

but When I go to dash board page, refresh time is still 15~20 seconds.

How can I change it to 5 sec?

**Comment by kesar** [comment]
That's probably the caching in the API side, are you using your own API or taking the one from eostracker api?

**Comment by newbieh4cker** [comment]
@kesar I'm using EOSTracker-API

**Comment by kesar** [comment]
https://github.com/EOSEssentials/EOSTracker-API/blob/master/src/AppBundle/Controller/DefaultController.php#L24

you need to remove cache or set it to a lower interval like 1

**Comment by newbieh4cker** [comment]
@kesar changed the interval, but When I go to dashboard page.
ERROR TypeError: t.map is not a function <-occurs

**Comment by newbieh4cker** [comment]
@kesar 
here is a thing.
When I use "https://api.eostracker.io" as apiUrl, it works good.
But, using my local api(cloend from EOSTracker-API), dashboard returns 
> main.1c5e95c051495cd32a3f.js:5000 ERROR TypeError: t.map is not a function

**Comment by tianyangj** [comment]
@newbieh4cker 
If you are using "map" operator, make sure you import {map} from 'rxjs/operators'.

**Comment by newbieh4cker** [comment]
@tianyangj 
Since It's working great with "api.eostracker.io", I think problem is EOSTracker-API.
But I'm not sure which file is causing problem.

**Comment by tianyangj** [comment]
If the issue is in EOSTracker-API, please open issue in that repo. I am closing this thread.
