### ISSUE TITLE
How to change token list for select?

### ISSUE THREAD

**Issue by newbieh4cker** [EOSEssentials/EOSTracker#66]
I've pulled latest EOSTrakcer-API to my local environment(which is using "ZZZ" as token symbol).
and When I go to "myip/EOSTracker/accounts/tester", browser console shows below error.

api < error 	 undefined //35.x.x.x:8888/v1/chain/get_currency_balance {"code":"therealkarma","account":"tester","symbol":"ADD"}

api < error 	 undefined //35.x.x.x:8888/v1/chain/get_currency_balance {"code":"therealkarma","account":"tester","symbol":"KARMA"}

it looks like those symbols are "AirDrop Token for EOS MainNet".
Is there anyways to change those symbol names?

**Comment by kesar** [comment]
in account.service where are using this:

```
  getTokens(): Observable<Token[]> {
    return this.http.get(`https://raw.githubusercontent.com/eoscafe/eos-airdrops/master/tokens.json`).pipe(
      map((tokens: any) => tokens.map(token => token as Token))
    );
  }
``` 

that gives an array similar to:

``` 

[{
--
  | "symbol": "EOS",
  | "account": "eosio.token"
  | },{
  | "symbol": "EOSDAC",
  | "account": "eosdactokens"
  | },{
  | "symbol": "ADD",
  | "account": "eosadddddddd"
  | },{
  | "symbol": "CETOS",
  | "account": "gyztomjugage"
  | },{
  | "symbol": "EOX",
  | "account": "eoxeoxeoxeox"
  | },{
  | "symbol": "EDNA",
  | "account": "ednazztokens"
  | },{
  | "symbol": "ATD",
  | "account": "eosatidiumio"
  | },{
  | "symbol": "CET",
  | "account": "eosiochaince"
  | },{
  | "symbol": "HORUS",
  | "account": "horustokenio"
  | },{
  | "symbol": "KARMA",
  | "account": "therealkarma"
  | }]
``` 

you could replace this method for an url that gives your own token, or just hardcode it there.

**Comment by newbieh4cker** [comment]
@kesar thanks!!
