### ISSUE TITLE
dashboard refresh time bug

### ISSUE THREAD

**Issue by newbieh4cker** [EOSEssentials/EOSTracker#67]
thanks to @kesar, I found ways to decrease refresh time.

I've  set https://github.com/EOSEssentials/EOSTracker-API/blob/master/src/AppBundle/Controller/DefaultController.php#L24 this to PT1S, and it works perfect.

However, I wanted to refresh dashboard every nano seconds, so I decided to comment entire line 24, and it didn't work. (something like 'no time define' error  occurs).

The problem is, when I uncomment line 24, EOSTracker main page(main-xxx.js) generatea 't.map' is not a function error.

**Comment by tianyangj** [comment]
This is probably related to EOSTracker-API project. I am closing this issue here, if you feel it is a front end issue, please let me know.
