### ISSUE TITLE
Transactions are not shown anymore

### ISSUE THREAD

**Issue by str** [EOSEssentials/EOSTracker#68]
I can't see latest transactions.

**Comment by tianyangj** [comment]
The latest transactions should be working now, closing this issue.

**Comment by str** [comment]
This is a transaction I can't see in the eostracker `81cf57832d763ee13e2d25f579786cbc8c5a84efbcc70e3d88d625314c00036b`

https://eostracker.io/transactions/81cf57832d763ee13e2d25f579786cbc8c5a84efbcc70e3d88d625314c00036b

The error log I see is:

```
"https://api.eostracker.io/transactions/81cf57832d763ee13e2d25f579786cbc8c5a84efbcc70e3d88d625314c00036b", 
ok: false, 
name: "HttpErrorResponse", 
message: "Http failure response for https://api.eostracker.io/transactions/81cf57832d763ee13e2d25f579786cbc8c5a84efbcc70e3d88d625314c00036b: 404 Not Found"
```
