### ISSUE TITLE
Failback transactions & blocks & accounts into blockchain

### ISSUE THREAD

**Issue by kesar** [EOSEssentials/EOSTracker#69]
If someone access to a transaction / block or account and API is down, we must show all info coming from blockchain API.

This will allow third parties to safely use our urls. In case that our API is down, we will show blockchain info.

**Comment by tianyangj** [comment]
I implemented failback logic in material-final branch, deployed to beta.eostracker.io.

One example is https://eostracker.io/blocks/1 returns error, but https://beta.eostracker.io/blocks/1 returns chain api data. I couldn't find any reliable errors fro transaction and account, but my local testing seems working.

**Comment by tianyangj** [comment]
@kesar, if we can get all data from chain api, does it still make sense calling our api first? Take a look at beta.eostracker.io, block detail page, https://beta.eostracker.io/blocks/9879391. All data required can be retrieved from chain API, in the network XHR, I didn't make any our own API call.

**Comment by kesar** [comment]
@tianyangj I was exactly thinking the same yday. We can use our API for only special stuff like block lists / tx lists / in account to filter actions (and in the future for stats and other data transformations 👍

**Comment by tianyangj** [comment]
Ok, sounds good. I am going to structure our data services in a way such that we will try chain api first. However, this is going to be challenging because we need to map out chain result to api result, also need to account for timestamp update etc.
