### ISSUE TITLE
Enable https

### ISSUE THREAD

**Issue by trungtt198x** [EOSEssentials/EOSTracker#70]
@kesar 
Could you please advise how to enable https for your wonderful eostracker?

I've tried out, but only successful at enabling https for the eos-tracker-frontend part while the backend-api is still with http. Thus, I get the following error:

```
polyfills.02561dc242715332215e.js:1 Mixed Content: The page at 'https://mydomain.io/accounts' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://some-IP:4201/accounts?page=1'. This request has been blocked; the content must be served over HTTPS.
```

Many thanks

**Comment by kesar** [comment]
you api endpoint is not over ssl, thats the problem

**Comment by trungtt198x** [comment]
@kesar 
Thanks much for your response.
I've also noticed this matter. 
Please advise how to enable SSL for the eos-tracker-api part? 
It's in PHP Symfony and should inside the file "app/.htaccess"? 
Could you share your configuration for this?

**Comment by tianyangj** [comment]
This is probably related to EOSTracker-API project. I am closing this issue here, if you feel it is a front end issue, please let me know.
