### ISSUE TITLE
hyperlink bug in detailed block page

### ISSUE THREAD

**Issue by newbieh4cker** [EOSEssentials/EOSTracker#81]
for example, in below page
https://eostracker.io/blocks/9662105

there is 'Previous Block Information' column and data(which is '00936e98e2c22b3213f8f36ec9e2c567093cf8fa20a3af787d6302738039a568')  with hyperlinked.

When I click that link, dashboard redirects to 'https://eostracker.io/search?q=00936e98e2c22b3213f8f36ec9e2c567093cf8fa20a3af787d6302738039a568', and recognize that data as transaction id, not block id.

so finally, dashboard goes to 'https://eostracker.io/transactions/00936e98e2c22b3213f8f36ec9e2c567093cf8fa20a3af787d6302738039a568' page.

So, I think  there are 2 options.
  1. modify search function, so we can search block info with Block id.
  2. just remove hyperlink from blocks page.

**Comment by tianyangj** [comment]
Yes, this is a bug. I will take a look.

**Comment by tianyangj** [comment]
@newbieh4cker, can you verify if this is still an issue for you?

**Comment by newbieh4cker** [comment]
@tianyangj 
working great, thanks for fixing it
